### ISSUE TITLE
视频横屏，有键盘弹出怎么搞，这种旋转不行吧

### ISSUE THREAD

**Issue by xjryuanmeng** [polyv/polyv-ios-cloudClass-sdk-demo#1]

**Comment by zykhbl** [comment]
是现在demo里视频横屏旋转有键盘弹出的bug（现在云课堂视频横屏是不会弹出键盘的，如果有弹出就是bug），还是你公司有需要在视频横屏时弹出键盘的业务需求？

**Comment by Zeaa** [comment]
转屏前先调用隐藏键盘方法，转屏后如有需要再弹出键盘

**Comment by xjryuanmeng** [comment]
全屏时，弹出键盘如何横屏呢

**Comment by xjryuanmeng** [comment]
我要在视频横屏时，显示有评论输入框，进行弹出键盘

**Comment by Zeaa** [comment]
@xjryuanmeng 0.8.0 版本是否解决了您的问题？
https://github.com/polyv/polyv-ios-cloudClass-sdk-demo/releases/tag/v0.8.0
