### ISSUE TITLE
云直播SDK（0.11.0）和云点播SDK（2.6.6）底层播放器能统一不？

### ISSUE THREAD

**Issue by jabbarwockeez** [polyv/polyv-ios-cloudClass-sdk-demo#2]
PolyvCloudClassSDK (= 0.11.0)对应PolyvIJKPlayer (~ > 0.6.0)
PolyvVodSDK (= 2.6.6)对应PolyvIJKPlayer (~ > 0.4.2)
PolyvIJKPlayer版本不一致，pod报错：
![image](https://user-images.githubusercontent.com/4702502/74150903-e5cb9400-4c45-11ea-8317-8aaa49c88fd1.png)

**Comment by Zeaa** [comment]
@jabbarwockeez 您把 PolyvVodSDK 版本改为 2.7.0 就行了，2.7.0 和 2.6.6 差异只在底层播放器

**Comment by jabbarwockeez** [comment]
> @jabbarwockeez 您把 PolyvVodSDK 版本改为 2.7.0 就行了，2.7.0 和 2.6.6 差异只在底层播放器

感谢，解决了我的问题！
